### ISSUE TITLE
请问 Snowing Game Engine 是否有提供 Rust Language Binding 的想法？

### ISSUE THREAD

**Issue by hzqd** [Strrationalism/Snowing#127]
@Seng-Jik 
您之前群聊中提到，如果有机会制作新的 visual novel 游戏引擎，会优先考虑 Rust 编程语言；但毕竟重新开发的成本比较昂贵，且这样的机会不一定会出现。您是否考虑过以二者交互的形式继续开发呢？

**Comment by Seng-Jik** [comment]
交互的成本也会很贵，我们具体之后的情况主要还是要看我们游戏的市场反应和游戏本身的需求。
不会考虑binding的方式。

**Comment by hzqd** [comment]
> 不会考虑binding的方式。

感谢您的明确答复！
