### ISSUE TITLE
需要允许在Windows下设置窗口和任务栏上的图标

### ISSUE THREAD

**Issue by Seng-Jik** [Strrationalism/Snowing#6]
可参考SDL的设置窗口图标来进行实现。

**Comment by Seng-Jik** [comment]
此issue需要在一个实际的游戏项目中实现。
应当在游戏中，根据本身的资源文件自动的加载并设置图标，不应当手动操作。

**Comment by Simakeng** [comment]
1. 设置Icon的功能应由window impl实现一个SetIcon函数
2. 而根据预设加载资源文件应实现一个预设加载器。
3. 图标文件建议以资源的形式编译进exe文件内

**Comment by Seng-Jik** [comment]
> * 设置Icon的功能应由window impl实现一个SetIcon函数
> * 而根据预设加载资源文件应实现一个预设加载器。
> * 图标文件建议以资源的形式编译进exe文件内

此操作对用户透明，引擎应当自动加载图标，不应当手动加载。
