### ISSUE TITLE
WindowImpl应该与input解耦

### ISSUE THREAD

**Issue by Simakeng** [Strrationalism/Snowing#78]
目前代码WindowImpl与input高度耦合

**Comment by Seng-Jik** [comment]
具体修改建议？

**Comment by Simakeng** [comment]
考虑采用Dinput8轮询或者WinAPI/GetKeyState轮询的方式读入输入

**Comment by Seng-Jik** [comment]
按键输入本身就是GetAsyncKeyState。
鼠标相关的某些输入使用Win消息机制。

**Comment by Simakeng** [comment]
鼠标输入也应采用GetAsyncKeyState，GetCursorPos，ScreenToClient来获取，以及消息队列存在动态内存分配的问题，建议考虑采用多线程处理消息。

**Comment by Seng-Jik** [comment]
不应当使用DInput，使用WinAPI完成，不使用动态内存，尽可能减少锁的使用，尽可能降低延迟。
语义必须和之前一致。
